import { QuizQuestion } from './types';

export const TIMER_DURATION = 15;

export const quizData: QuizQuestion[] = [
    {
        id: 1,
        type: "주제/목적 추론",
        question: "Why did Mia Watson and her club organize the volunteer trip to the animal sanctuary?",
        options: [
            "To rescue all the animals from illegal farms.",
            "To get credits for their community service requirements.",
            "To learn about animal care in a safe and caring environment.",
            "To help the staff members clean the facility for two weeks.",
            "To organize a new club at the sanctuary.",
        ],
        answerIndex: 2,
        explanation: "지문 Page 17에서 'All the club members and I agreed that the sanctuary would be the perfect place to learn about animal care.'라고 명시하고 있습니다. 봉사 활동의 주된 목적은 '동물 보호에 대해 배우는 것'이었습니다.",
    },
    {
        id: 2,
        type: "세부 사실 확인",
        question: "Which of the following activities was performed by the club members on **July 29, Monday**?",
        options: [
            "Setting up the 'digital bridge' for a paralyzed animal.",
            "Providing emergency treatment and vitamins to dehydrated birds.",
            "Cleaning the shelter and preparing food for the animals.",
            "Making honey-log feeders for Ben and Lily.",
            "Conducting positive reinforcement training for Molly.",
        ],
        answerIndex: 2,
        explanation: "Page 18에 따르면 월요일(July 29)의 임무(tasks for the day)는 'cleaning the shelter and preparing food for the animals'였습니다.",
    },
    {
        id: 3,
        type: "추론적 이해",
        question: "Why did the volunteers need to chop bananas instead of sugarcane for some elephants?",
        options: [
            "Bananas are their favorite fruit and the elephants only eat them.",
            "The old elephants had weak teeth, making it hard to chew sugarcane.",
            "The sanctuary ran out of sugarcane supplies that day.",
            "Sugarcane was part of the 'behavioral enrichment' program.",
            "Bananas were used as a reward in the training sessions.",
        ],
        answerIndex: 1,
        explanation: "Page 18의 내용 중 'For old elephants with weak teeth, we chopped bananas instead of the sugarcane...'에서 이가 약한 코끼리를 위한 배려임을 알 수 있습니다.",
    },
    {
        id: 4,
        type: "문맥상 어휘 추론",
        question: "Based on the context of the story, what is the best word to describe the volunteers' experience when helping the animals (Page 18)?\n\nIt was a ____________ experience, and I was impressed with the attention the staff members gave to all the animals.",
        options: [
            "frustrating",
            "exhausting",
            "rewarding",
            "disturbing",
            "confusing",
        ],
        answerIndex: 2,
        explanation: "직원들의 애정에 감명받았다는 문맥과 함께, 동물들을 돕는 경험은 긍정적인 의미인 '보람 있는(rewarding)'이 가장 적절합니다.",
    },
    {
        id: 5,
        type: "행동의 목적 추론",
        question: "What is the primary goal of the 'positive reinforcement training' used for Molly, the elderly elephant?",
        options: [
            "To teach Molly to perform tricks for tourists.",
            "To encourage her to move her body more to lose weight.",
            "To reduce the stress she experiences during controlled situations like treatment or health examination.",
            "To make her spine straight again by lifting her feet.",
            "To introduce her to a new favorite food, watermelon.",
        ],
        answerIndex: 2,
        explanation: "Page 20에서 'This training helps reduce the stress that animals experience during controlled situations, such as treatment or a health examination.'라고 목적을 설명하고 있습니다.",
    },
    {
        id: 6,
        type: "주제/교훈 파악",
        question: "What was the narrator's ultimate realization ('I also came to realize...') on the last day of volunteering?",
        options: [
            "That climate change can only harm birds.",
            "That humans are solely responsible for all animal problems.",
            "That humans are just another kind of animal sharing the Earth with all other living creatures.",
            "That she must become a veterinarian to save animals.",
            "That it is more important to save birds than elephants.",
        ],
        answerIndex: 2,
        explanation: "Page 21의 마지막 날 일기에서 'I also came to realize that humans are just another kind of animal and share the Earth with all other living creatures.'라는 중요한 깨달음을 얻었다고 언급합니다.",
    },
    {
        id: 7,
        type: "빈칸 채우기 (핵심 어휘)",
        question: "To help the bears recover their natural instincts, the staff members carried out special activities known as '____________ enrichment'.",
        options: [
            "cognitive",
            "emotional",
            "behavioral",
            "physical",
            "spiritual",
        ],
        answerIndex: 2,
        explanation: "Page 19에 따르면 곰들이 타고난 본능을 회복하도록 돕기 위해 '행동 풍부화(behavioral enrichment)' 활동을 시행했습니다. 핵심 어휘 'behavioral'을 정확히 이해해야 합니다.",
    },
    {
        id: 8,
        type: "어법/어휘 선택",
        question: "Choose the grammatically correct or contextually appropriate words for (A) and (B):\n\n\"It was a **(A) rewarding / rewarded** experience, and I was **(B) impressed / impressing** with the attention the staff members gave to all the animals.\"",
        options: [
            "(A) rewarding / (B) impressed",
            "(A) rewarded / (B) impressing",
            "(A) rewarding / (B) impressing",
            "(A) rewarded / (B) impressed",
            "(A) rewarding / (B) impress",
        ],
        answerIndex: 0,
        explanation: "(A) 경험은 '보람을 주는' 것이므로 현재분사 **rewarding**이 맞습니다. (B) 나는 감명을 '받은' 것이므로 감정의 수동을 나타내는 과거분사 **impressed**가 맞습니다. (Page 18)",
    },
    {
        id: 9,
        type: "빈칸 채우기 (구문)",
        question: "The positive reinforcement training used for Molly involves using rewards to reinforce **____________** behavior.",
        options: [
            "undesirable",
            "aggressive",
            "desirable",
            "destructive",
            "negative",
        ],
        answerIndex: 2,
        explanation: "긍정 행동 강화 훈련(positive reinforcement training)은 '바람직한(desirable) 행동'을 강화하는 데 보상을 이용합니다. (Page 20)",
    },
    {
        id: 10,
        type: "어법 틀린 곳 고르기",
        question: "다음 문장에서 어법상 **틀린** 것을 고르시오. (Page 17/18 기반)\n\nFor old elephants with weak teeth, we chopped bananas **(D) instead** the sugarcane that they usually eat.",
        options: [
            "(A) where",
            "(B) moving",
            "(C) for",
            "(D) instead",
            "(E) impressed",
        ],
        answerIndex: 3,
        explanation: "오답은 **(D) instead**입니다. **instead**는 부사이므로 '... 대신에'라는 의미로 명사(the sugarcane)를 받을 때는 전치사 **of**가 필요합니다. 'instead of'가 바른 표현입니다. (A) 관계부사, (B) 지각동사 see의 목적격 보어, (C) 전치사, (E) 감정의 수동(감명받은)으로 모두 적절합니다.",
    },
];
